server:
  port: 8787

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: urt889
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none